tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - ritwickdey.LiveServer@5.6.1:5Mhl1RgVVDcIym163x8r+w==